jan26_cde_crypto_streamlit:
  outputs:
    dev:
      dataset: db_crypto
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west1
      method: oauth
      project: jan26-cde-crypto
      threads: 2
      type: bigquery
  target: dev